Repository peeratmac/movie-tracker, pull requests merged in 2019-10, with the labels that each got.

#1 Add DTR document
  planning/DTR.md
Labels: documentation

#10 Login feature - update with state use of redux
  src/actions/index.js
  src/components/App/App.js
  src/components/LoginForm/LoginForm.js
  src/containers/RegisterForm/RegisterForm.js
  src/reducers/error.js
  src/reducers/index.js
  src/reducers/isLoggedIn.js
  src/reducers/user.js
Labels: initial-step-toward-mvp, refactor-improvements

#11 Testing
  src/Header/header.scss
  src/actions/actions.test.js
  src/components/App/App.test.js
  src/components/LoginForm/LoginForm.js
  src/components/LoginForm/LoginForm.test.js
  src/components/LoginForm/__snapshots__/LoginForm.test.js.snap
  src/components/MovieCard/MovieCard.scss
  src/setupTests.js
Labels: testing

#12 User specific feature and favorites (sign in and sign out, display users, update state to redux)
  src/Header/header.js
  src/actions/index.js
  src/components/LoginForm/LoginForm.js
  src/components/MovieCard/MovieCard.js
  src/images/star-favorited.svg
  src/images/star-white.svg
  src/reducers/user.js
Labels: important-mvp, refactor-improvements, styling

#14 Dynamic button renders
  src/Header/header.js
  src/actions/index.js
  src/apiCalls.js
  src/components/App/App.js
  src/components/LoginForm/LoginForm.js
  src/containers/RegisterForm/RegisterForm.js
  src/reducers/error.js
  src/reducers/user.js
Labels: important-mvp

#15 Favorite user specific feature
  src/actions/index.js
  src/apiCalls.js
  src/components/App/App.js
  src/components/LoginForm/LoginForm.js
  src/reducers/favorites.js
  src/reducers/index.js
  src/reducers/user.js
Labels: important-mvp, refactor-improvements

#17 Update MovieInfo container
  src/components/App/App.js
  src/components/MovieCard/MovieCard.js
  src/components/MovieInfo/MovieInfo.js
  src/containers/MoviesContainer/MoviesContainer.js
  src/reducers/index.js
  src/reducers/selectMovie.js
Labels: refactor-improvements, styling

#18 Favoriting
  src/Header/header.js
  src/actions/index.js
  src/apiCalls.js
  src/components/App/App.js
  src/components/LoginForm/LoginForm.js
  src/components/MovieCard/MovieCard.js
  src/containers/RegisterForm/RegisterForm.js
  src/reducers/addMovies.js
  src/reducers/favorites.js
Labels: important-mvp

#21 Displaying favorites - favorites button/tab display when user signed in - specific user favorites
  src/Favorites/Favorites.js
  src/Header/header.js
  src/actions/index.js
  src/components/App/App.js
  src/reducers/displayFavorites.js
  src/reducers/index.js
Labels: help wanted, important-mvp, refactor-improvements

#22 Testing updated
  src/actions/actions.test.js
  src/components/App/App.js
  src/components/App/App.test.js
  src/components/LoginForm/LoginForm.test.js
  src/components/MovieCard/MovieCard.js
  src/reducers/addMovies.test.js
  src/reducers/error.test.js
  src/reducers/favorites.test.js
  src/reducers/isLoggedIn.test.js
  src/reducers/selectMovie.js
  src/reducers/selectMovie.test.js
  src/reducers/tempUser.test.js
Labels: important-mvp, testing

#25 Api calls testing
  src/apiCalls.js
  src/apiCalls.test.js
  src/components/App/App.js
  src/components/MovieCard/MovieCard.js
Labels: important-mvp

#24 New branch
  src/Favorites/Favorites.js
  src/Favorites/Favorites.scss
  src/components/LoginForm/LoginForm.js
  src/components/MovieCard/MovieCard.js
  src/components/MovieCard/MovieCard.scss
  src/components/MovieInfo/MovieInfo.js
  src/components/MovieInfo/MovieInfo.scss
  src/containers/MoviesContainer/MovieContainers.scss
  src/containers/RegisterForm/RegisterForm.js
  src/containers/RegisterForm/RegisterForm.scss
Labels: styling

#26 Final style
  src/Favorites/Favorites.scss
  src/Header/header.scss
  src/components/App/App.scss
  src/components/LoginForm/LoginForm.js
  src/components/LoginForm/LoginForm.scss
  src/components/MovieCard/MovieCard.js
  src/components/MovieCard/MovieCard.scss
  src/components/MovieInfo/MovieInfo.scss
  src/containers/MoviesContainer/MovieContainers.scss
  src/containers/RegisterForm/RegisterForm.js
  src/containers/RegisterForm/RegisterForm.scss
Labels: styling

#28 Add PropTypes to all components
  package-lock.json
  package.json
  src/Favorites/Favorites.js
  src/Header/header.js
  src/components/App/App.js
  src/components/LoginForm/LoginForm.js
  src/components/MovieCard/MovieCard.js
  src/components/MovieInfo/MovieInfo.js
Labels: refactor-improvements, testing

#32 Persiting logged in
  package-lock.json
  package.json
  src/Header/header.js
  src/components/App/App.js
  src/components/LoginForm/LoginForm.js
  src/components/MovieCard/MovieCard.js
  src/components/MovieInfo/MovieInfo.js
  src/containers/RegisterForm/RegisterForm.js
Labels: enhancement, important-mvp

#33 Ugh
  src/actions/actions.test.js
  src/components/LoginForm/LoginForm.test.js
  src/components/MovieCard/__snapshots__/MovieCard.test.js.snap
  src/containers/RegisterForm/RegisterForm.test.js
Labels: testing

#34 Linting
  .eslintrc.json
  package-lock.json
  package.json
  src/Favorites/Favorites.js
  src/Header/header.js
  src/actions/Login.js
  src/apiCalls.js
  src/apiCalls.test.js
  src/components/App/App.js
  src/components/LoginForm/LoginForm.scss
  src/containers/RegisterForm/RegisterForm.scss
  src/reducers/addMovies.js
  src/reducers/displayFavorites.js
  src/reducers/error.js
  src/reducers/tempUser.js
Labels: documentation, enhancement, important-mvp
